#!/usr/bin/env bash

interval=0

cpu() {
	cpu_val=$(grep -o "^[^ ]*" /proc/loadavg)
	printf "CPU"
	printf "$cpu_val"
}

pkg_updates() {
	updates=$({ timeout 20 checkupdates 2>/dev/null || true; } | wc -l)

	if [ "$updates" -eq 0 ]; then
		printf " Fully Updated"
	else
		printf "$updates"" updates"
	fi
}

battery() {
	CHARGE=$(cat /sys/class/power_supply/BAT1/capacity)
	STATUS=$(cat /sys/class/power_supply/BAT1/status)
	if [ "$STATUS" = "Charging" ]; then
		printf " $CHARGE%% $STATUS " 
	else
		printf " $CHARGE%% $STATUS "
	fi
}

brightness() {
	printf "  "
	printf "$(cat /sys/class/backlight/*/brightness)"
}

mem() {
	printf " "
	printf "$(free -h | awk '/^Mem/ { print $3 }' | sed s/i//g)"
}

wlan() {
	case "$(cat /sys/class/net/wl*/operstate 2>/dev/null)" in
		up) printf "󰤨 Connected" ;;
		down) printf "󰤭 Disconnected" ;;
	esac
}

clock() {
	clock=$(date '+%I')

	case "$clock" in
		"00") icon="󱑊" ;;
		"01") icon="󱐿" ;;
		"02") icon="󱑀" ;;
		"03") icon="󱑁" ;;
		"04") icon="󱑂" ;;
		"05") icon="󱑃" ;;
		"06") icon="󱑄" ;;
		"07") icon="󱑅" ;;
		"08") icon="󱑆" ;;
		"09") icon="󱑇" ;;
		"10") icon="󱑈" ;;
		"11") icon="󱑉" ;;
		"12") icon="󱑊" ;;
	esac


	printf "$icon "
	printf "$(date '+%H:%M')"
}

calender() {
	printf " "
	printf "$(date '+%D')"
}

vol_bar() {
	vol="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"

	# If muted, print 󰖁 and exit.
	[ "$vol" != "${vol%\[MUTED\]}" ] && printf "󰖁 MUTED" && exit
	
	vol="${vol#Volume: }"
	
	split() {
		# For ommiting the . without calling and external program.
		IFS=$2
		set -- $1
		printf '%s' "$@"
	}
	
	vol="$(printf "%.0f" "$(split "$vol" ".")")"
	
	case 1 in
		$((vol >= 70)) ) icon="" ;;
		$((vol >= 30)) ) icon="" ;;
		$((vol >= 1)) ) icon="" ;;
		* ) printf " 󰖁 " && exit ;;
	esac
	
	printf "$icon$vol%%"
}

weather() {
	LOCATION=Berlin
	DATA=$(curl -s wttr.in/$LOCATION?format=1 | grep -o ".[0-9].*")
	printf " ${DATA}"
}

while true; do

  [ $interval = 0 ] || [ $(($interval % 3600)) = 0 ] && updates=$(pkg_updates)
  interval=$((interval + 1))

  sleep 1 && xsetroot -name "$updates | $(weather) | $(vol_bar) | $(cpu) | $(mem) | $(wlan) | $(clock) | $(calender)"
done
