env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_STYLE_OVERRIDE,kvantum

# env = WLR_DRM_NO_ATOMIC,1
env = GDK_BACKEND,wayland,x11
env = CLUTTER_BACKEND,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland

# firefox
env = MOZ_ENABLE_WAYLAND,1
<<<<<<< HEAD

# hyprcursor
env = HYPRCURSOR_THEME,MyCursor
env = HYPRCURSOR_SIZE,24
=======
>>>>>>> main
